spring.application.name=optifit-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/optifit_db
spring.datasource.username=optifit_user
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080